// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbpPjvvfqJXDm0cN7qqrpuyZn-sDGWeZc',
    appId: '1:383677905477:web:04dca032ee94444e8c812c',
    messagingSenderId: '383677905477',
    projectId: 'apt-vine-442908-c7',
    authDomain: 'apt-vine-442908-c7.firebaseapp.com',
    storageBucket: 'apt-vine-442908-c7.firebasestorage.app',
    measurementId: 'G-EVVXT76EGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmefzCi2zmyLsQ2s0xV8DukYxx5QrzAoM',
    appId: '1:383677905477:android:f77deeb2d09f7bbc8c812c',
    messagingSenderId: '383677905477',
    projectId: 'apt-vine-442908-c7',
    storageBucket: 'apt-vine-442908-c7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbpPjvvfqJXDm0cN7qqrpuyZn-sDGWeZc',
    appId: '1:383677905477:web:62bb6bc2032575ac8c812c',
    messagingSenderId: '383677905477',
    projectId: 'apt-vine-442908-c7',
    authDomain: 'apt-vine-442908-c7.firebaseapp.com',
    storageBucket: 'apt-vine-442908-c7.firebasestorage.app',
    measurementId: 'G-YHSYBVVFNL',
  );
}
